# staging build

branches:
  only:
    - staging

branches:
  only:
    - master

language: node_js

node_js:
  - "6.9.4"

install:
  - export PATH=$PATH:$HOME/.local/bin
  - sudo pip install awscli
  - npm install

script:
  - npm run test

after_success:
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: $STAGING_BUCKET_NAME
  local_dir: "./www"
  skip_cleanup: true

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $STAGING_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"