language: node_js

node_js:
  - "6.9.4"

install:
  - export PATH=$PATH:$HOME/.local/bin
  - sudo pip install awscli
  - npm install

script:
  - npm run test

after_success:
  - npm run build

deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  local_dir: "./www"
  skip_cleanup: true

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

# addons:
#   s3_region: "us-east-1"
#   debug: true
#   artifacts: 
#     paths:
#       - $ARTIFACTS_PATH