export const CLAUSE_ADD = '@CLAUSE/CLAUSE_ADD'
export const CLAUSE_REMOVE = '@CLAUSE/CLAUSE_REMOVE'
export const CLAUSE_CHANGE_NAME = '@CLAUSE/CHANGE_NAME'

export const CLAUSE_INVALID_REGEXP = '@CLAUSE/CLAUSE_INVALID_REGEXP'
export const CLAUSE_INVALID_ATTRKEY = '@CLAUSE/CLAUSE_INVALID_ATTRKEY'

export const QUERY_ADD = '@CLAUSE/QUERY_ADD'
export const QUERY_REMOVE = '@CLAUSE/QUERY_REMOVE'

export const QUERY_CHANGE_TARGET = '@CLAUSE/QUERY_CHANGE_TARGET'
export const QUERY_CHANGE_TARGET_VALUE = '@CLAUSE/QUERY_CHANGE_TARGET_VALUE'
export const QUERY_CHANGE_RULE = '@CLAUSE/QUERY_CHANGE_RULE'
export const QUERY_CHANGE_RULE_VALUE = '@CLAUSE/QUERY_CHANGE_RULE_VALUE'
export const QUERY_CHANGE_RULE_VALUE_FLAGS = '@CLAUSE/QUERY_CHANGE_RULE_VALUE_FLAGS'

export const MUTATION_ADD = '@CLAUSE/MUTATION_ADD'
export const MUTATION_REMOVE = '@CLAUSE/MUTATION_REMOVE'

export const MUTATION_ADD_ATTR = '@CLAUSE/MUTATION_ADD_ATTR'
export const MUTATION_REMOVE_ATTR_BY_KEY = '@CLAUSE/MUTATION_REMOVE_ATTR_BY_KEY'
export const MUTATION_REMOVE_ATTR_BY_VALUE = '@CLAUSE/MUTATION_REMOVE_ATTR_BY_VALUE'
export const MUTATION_REMOVE_ALL_ATTRS = '@CLAUSE/MUTATION_REMOVE_ALL_ATTRS'

