export const HTML_RAW_CHANGE = '@SOURCESETTER/HTML_RAW_CHANGE'
export const URL_CHANGE = '@SOURCESETTER/URL_CHANGE'
export const SET_HTML = '@SOURCESETTER/SET_HTML'

export const HTML_FETCHED = '@SOURCESETTER/HTML_FETCHED'
export const SOURCE_SUBMIT = '@SOURCESETTER/SOURCE_SUBMIT'

export const FILE_READ_INIT = '@SOURCESETTER/FILE_READ_INIT'
export const FILE_READ_DONE = '@SOURCESETTER/FILE_READ_DONE'
export const FILE_READ_ERROR = '@SOURCESETTER/FILE_READ_ERROR'

export const FETCH_URL_INIT = '@SOURCESETTER/FETCH_URL_INIT'
export const FETCH_URL_DONE = '@SOURCESETTER/FETCH_URL_DONE'
export const FETCH_URL_ERROR = '@SOURCESETTER/FETCH_URL_ERROR'

export const DISMISS_MODAL = '@SOURCESETTER/DISMISS_MODAL'
export const CALL_MODAL = '@SOURCESETTER/CALL_MODAL'